// Generated by CoffeeScript 1.8.0
(function() {
  var rfile;

  rfile = require("./..");

  rfile("./tests/small.txt").then(console.log)["catch"](function(err) {
    throw err;
  });

}).call(this);
